micronaut:
  io:
    watch:
      paths: src/main
      restart: true
  application:
    name: blog-back
  server:
    port: 8081


datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2



jpa:
  default:
    packages-to-scan:
      - 'service.test'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
#        show_sql: true


